name: Daily Auto Push

on:
  schedule:
    - cron: '0 0 * * *'  # 매일 자정에 실행
  workflow_dispatch:  # 수동 실행 가능

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        lfs: true
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git config --global core.quotepath false
        
    - name: Debug Info
      run: |
        echo "현재 디렉토리 내용:"
        ls -la
        echo "Git 상태:"
        git status
        
    - name: Check and commit changes
      run: |
        git add Emp_Data.xlsx
        git add salary_table.xlsx
        
        if git diff --staged --quiet; then
          echo "변경사항이 없습니다."
          exit 0
        else
          echo "변경사항이 있습니다."
          git commit -m "Update: 엑셀 파일 자동 업데이트"
          git push origin master
        fi