name: Daily Auto Push

on:
  schedule:
    # 매일 오전 8시에 실행 (UTC+9 기준)
    - cron: '0 23 * * *'  # UTC 기준 23시 = 한국 시간 오전 8시
  workflow_dispatch:  # 수동 실행 옵션 추가

jobs:
  auto-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
        lfs: true

    - name: Set up Git LFS
      run: |
        git lfs install
        git lfs pull
        
    - name: Set up Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git config --global lfs.locksverify false

    - name: Debug Info
      run: |
        echo "현재 디렉토리 내용:"
        ls -la
        echo "Git 상태:"
        git status
        echo "Git LFS 상태:"
        git lfs status
        
    - name: Check for changes and push
      run: |
        # Git LFS 트래킹 설정
        git lfs track "*.xlsx"
        git add .gitattributes
        
        # 엑셀 파일 변경사항 확인 및 추가
        if [ -f "임직원 기초 데이터.xlsx" ]; then
          echo "엑셀 파일 찾음, 변경사항 확인 중..."
          git add -f "임직원 기초 데이터.xlsx"
          git lfs status
        else
          echo "엑셀 파일을 찾을 수 없습니다."
        fi
        
        # app.py 파일 추가
        if [ -f "app.py" ]; then
          git add app.py
        fi
        
        # 변경사항 확인 및 커밋
        if git status --porcelain | grep -q '^[MAD]'; then
          echo "변경사항이 감지되었습니다."
          current_date=$(date '+%Y-%m-%d %H:%M:%S')
          git commit -m "Update: 임직원 기초 데이터 업데이트 (${current_date})"
          git push origin master
          echo "변경사항이 성공적으로 푸시되었습니다."
        else
          echo "푸시할 변경사항이 없습니다."
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}