name: Daily Auto Push

on:
  schedule:
    # 매일 오전 8시에 실행 (UTC+9 기준)
    - cron: '0 23 * * *'  # UTC 기준 23시 = 한국 시간 오전 8시
  workflow_dispatch:  # 수동 실행 옵션 추가

jobs:
  auto-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Set up Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Check for changes and push
      run: |
        git add app.py "임직원 기초 데이터.xlsx"
        current_date=$(date '+%Y-%m-%d')
        git commit -m "Daily auto-push: ${current_date}" || echo "No changes to commit"
        git push origin master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}