name: Daily Auto Push

on:
  schedule:
    - cron: '0 0 * * *'  # 매일 자정에 실행
  workflow_dispatch:  # 수동 실행 가능

jobs:
  push:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        lfs: true
        
    - name: Set up Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git config --global core.quotepath false
        
    - name: Set up Git LFS
      run: |
        git lfs install
        git lfs track "*.xlsx"
        git add .gitattributes
        
    - name: Check and commit changes
      run: |
        # 파일 이름에 공백이 있는 경우를 위해 따옴표로 감싸서 처리
        FILES=("임직원 기초 데이터.xlsx" "salary_table.xlsx")
        for file in "${FILES[@]}"; do
          if [ -f "$file" ]; then
            git add "$file"
          fi
        done
        
        if git diff --staged --quiet; then
          echo "No changes detected"
          exit 0
        else
          git commit -m "Update: 엑셀 파일 자동 업데이트"
          git push origin master
        fi